### PR TITLE
Initial Library Implementation. 

### PR DESCRIPTION
**Pull request by DennisSmolek**
Not sure we should merge onto main yet. There's no readme and I'm not 100% on the state of things just yet.

However I'm hoping this PR shows me the vercel hosted versions of the demo...

### CODE REVIEW

**Comment by DennisSmolek** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Updated (UTC)
> **react-three-jolt**	❌ Failed ([Inspect](https://vercel.com/pmndrs/react-three-jolt/8MrYtL7Vmynvath5DqUXfCU3waPR))		Apr 12, 2024 4:07pm

@isaac-mason can you take a look in Vercel why this is failing there? 
As mentioned I'm not sure this should go on main yet, but I was hoping the demo would go up.

**Comment by isaac-mason** [comment]
@DennisSmolek looks like it's failing on type errors in the examples app.

**Comment by DennisSmolek** [comment]
> @DennisSmolek looks like it's failing on type errors in the examples app.

Ahh ok. I was being lazy there and my local is building. I'll work on it.

**Comment by isaac-mason** [comment]
@DennisSmolek Ah yep vite dev doesn't fail on types. Also, let's get you vercel access!

**Comment by DennisSmolek** [comment]
@isaac-mason can you take a look at Vercel?
I updated the readme using Github's MD editor yet somehow that's making the build fail now.. 

I copied the header from R3/Rapier so I know it should take HTML ok. 

I still dont have Vercel access so I can't see the log

**Comment by isaac-mason** [comment]
@DennisSmolek fixed the issue with README.md now.

The root README.md is a symlink to packages/react-three-jolt/README.md, so when we edited README.md we actually made a very large symlink that git didn't know how to handle.

I've fixed the README.md symlink, and moved all your README.md changes to packages/react-threejolt/README.md.

**Pull request merged**
